on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C4
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/mnist-sample.git
      url: context.event.github.url
      ref: context.event.github.ref
    outputs:
      mnist-sample:
        type: volume
  TrainModel:
    resources:
      instance-type: C4
    env:
      PS_MODEL_PATH: /my-trained-model
    uses: container@v1
    with:
      args:
        - bash
        - -c
        - >-
          cd /inputs/mnist-sample && python test.py
      image: registry.digitalocean.com/bullit-digital/bergnet-feature-store:main_13
      containerRegistry: bullit-digital
    needs:
      - CloneRepo
    inputs:
      mnist-sample: CloneRepo.outputs.mnist-sample
      test-data:
        type: dataset
        with:
          ref: dsefhhkkncfltk0
